import { Component } from '@angular/core';

/**
 *
 */
@Component({
    selector: 'app-root',
    templateUrl: './app.component.html',
    styleUrls: ['./app.component.scss'],
})
export class AppComponent {
    public contactArray = getMockPeople();
}

/**
 *
 */
function getMockPeople(): any[] {
    return [
        {
            DisplayName: 'test',
            MemberID: 'F001',
            Email: 'test@test.com',
            Phone: '253-414-8432',
            ProfilePicture: '',
        },
        {
            DisplayName: 'Mohammad',
            MemberID: 'F001b',
            Email: 'test@test.com',
            Phone: '781-840-5773',
            ProfilePicture: '',
        },
        {
            DisplayName: 'Hossein Azizkhani',
            MemberID: 'F002',
            Email: 'HosseinAzizkhani@TEI.com',
            Phone: '315-673-8759',
            ProfilePicture: 'https://en.gravatar.com/userimage/202136773/a558891c4ea05046cf2dcc00616153fe.jpg',
        },
        {
            DisplayName: 'Ian Robinson',
            MemberID: 'F001',
            Email: 'IanRobinson@TEI.com',
            Phone: '253-414-8432',
            ProfilePicture: '',
        },
        {
            DisplayName: 'Mohammad Chavoshi',
            MemberID: 'F001b',
            Email: 'MohammadChavoshi@TEI.com',
            Phone: '781-840-5773',
            ProfilePicture: '',
        },
        {
            DisplayName: 'Hossein Azizkhani',
            MemberID: 'F002',
            Email: 'HosseinAzizkhani@TEI.com',
            Phone: '315-673-8759',
            ProfilePicture: 'https://en.gravatar.com/userimage/202136773/a558891c4ea05046cf2dcc00616153fe.jpg',
        },
        {
            DisplayName: 'Pegah Khavarifar',
            MemberID: 'F002a',
            Email: 'PegahKhavarifar@TEI.com',
            Phone: '289-407-1155',
            ProfilePicture: '',
        },
        {
            DisplayName: 'Moein Shafiei',
            MemberID: 'F002b',
            Email: 'MoeinShafiei@TEI.com',
            Phone: '361-388-4363',
            ProfilePicture: '',
        },
        {
            DisplayName: 'Ian Robinson',
            MemberID: 'F001',
            Email: 'IanRobinson@TEI.com',
            Phone: '253-414-8432',
            ProfilePicture: '',
        },
        {
            DisplayName: 'Mohammad Chavoshi',
            MemberID: 'F001b',
            Email: 'MohammadChavoshi@TEI.com',
            Phone: '781-840-5773',
            ProfilePicture: '',
        },
        {
            DisplayName: 'Hossein Azizkhani',
            MemberID: 'F002',
            Email: 'HosseinAzizkhani@TEI.com',
            Phone: '315-673-8759',
            ProfilePicture: 'https://en.gravatar.com/userimage/202136773/a558891c4ea05046cf2dcc00616153fe.jpg',
        },
        {
            DisplayName: 'Pegah Khavarifar',
            MemberID: 'F002a',
            Email: 'PegahKhavarifar@TEI.com',
            Phone: '289-407-1155',
            ProfilePicture: '',
        },
        {
            DisplayName: 'Moein Shafiei',
            MemberID: 'F002b',
            Email: 'MoeinShafiei@TEI.com',
            Phone: '361-388-4363',
            ProfilePicture: '',
        },
        {
            DisplayName: 'Ian Robinson',
            MemberID: 'F001',
            Email: 'IanRobinson@TEI.com',
            Phone: '253-414-8432',
            ProfilePicture: '',
        },
        {
            DisplayName: 'Mohammad Chavoshi',
            MemberID: 'F001b',
            Email: 'MohammadChavoshi@TEI.com',
            Phone: '781-840-5773',
            ProfilePicture: '',
        },
        {
            DisplayName: 'Hossein Azizkhani',
            MemberID: 'F002',
            Email: 'HosseinAzizkhani@TEI.com',
            Phone: '315-673-8759',
            ProfilePicture: 'https://en.gravatar.com/userimage/202136773/a558891c4ea05046cf2dcc00616153fe.jpg',
        },
        {
            DisplayName: 'Pegah Khavarifar',
            MemberID: 'F002a',
            Email: 'PegahKhavarifar@TEI.com',
            Phone: '289-407-1155',
            ProfilePicture: '',
        },
        {
            DisplayName: 'Moein Shafiei',
            MemberID: 'F002b',
            Email: 'MoeinShafiei@TEI.com',
            Phone: '361-388-4363',
            ProfilePicture: '',
        },
        {
            DisplayName: 'Ian Robinson',
            MemberID: 'F001',
            Email: 'IanRobinson@TEI.com',
            Phone: '253-414-8432',
            ProfilePicture: '',
        },
        {
            DisplayName: 'Mohammad Chavoshi',
            MemberID: 'F001b',
            Email: 'MohammadChavoshi@TEI.com',
            Phone: '781-840-5773',
            ProfilePicture: '',
        },
        {
            DisplayName: 'Hossein Azizkhani',
            MemberID: 'F002',
            Email: 'HosseinAzizkhani@TEI.com',
            Phone: '315-673-8759',
            ProfilePicture: 'https://en.gravatar.com/userimage/202136773/a558891c4ea05046cf2dcc00616153fe.jpg',
        },
        {
            DisplayName: 'Pegah Khavarifar',
            MemberID: 'F002a',
            Email: 'PegahKhavarifar@TEI.com',
            Phone: '289-407-1155',
            ProfilePicture: '',
        },
        {
            DisplayName: 'Moein Shafiei',
            MemberID: 'F002b',
            Email: 'MoeinShafiei@TEI.com',
            Phone: '361-388-4363',
            ProfilePicture: '',
        },
        {
            DisplayName: 'Ian Robinson',
            MemberID: 'F001',
            Email: 'IanRobinson@TEI.com',
            Phone: '253-414-8432',
            ProfilePicture: '',
        },
        {
            DisplayName: 'Mohammad Chavoshi',
            MemberID: 'F001b',
            Email: 'MohammadChavoshi@TEI.com',
            Phone: '781-840-5773',
            ProfilePicture: '',
        },
        {
            DisplayName: 'Hossein Azizkhani',
            MemberID: 'F002',
            Email: 'HosseinAzizkhani@TEI.com',
            Phone: '315-673-8759',
            ProfilePicture: 'https://en.gravatar.com/userimage/202136773/a558891c4ea05046cf2dcc00616153fe.jpg',
        },
        {
            DisplayName: 'Pegah Khavarifar',
            MemberID: 'F002a',
            Email: 'PegahKhavarifar@TEI.com',
            Phone: '289-407-1155',
            ProfilePicture: '',
        },
        {
            DisplayName: 'Moein Shafiei',
            MemberID: 'F002b',
            Email: 'MoeinShafiei@TEI.com',
            Phone: '361-388-4363',
            ProfilePicture: '',
        },
        {
            DisplayName: 'Ian Robinson',
            MemberID: 'F001',
            Email: 'IanRobinson@TEI.com',
            Phone: '253-414-8432',
            ProfilePicture: '',
        },
        {
            DisplayName: 'Mohammad Chavoshi',
            MemberID: 'F001b',
            Email: 'MohammadChavoshi@TEI.com',
            Phone: '781-840-5773',
            ProfilePicture: '',
        },
        {
            DisplayName: 'Hossein Azizkhani',
            MemberID: 'F002',
            Email: 'HosseinAzizkhani@TEI.com',
            Phone: '315-673-8759',
            ProfilePicture: 'https://en.gravatar.com/userimage/202136773/a558891c4ea05046cf2dcc00616153fe.jpg',
        },
        {
            DisplayName: 'Pegah Khavarifar',
            MemberID: 'F002a',
            Email: 'PegahKhavarifar@TEI.com',
            Phone: '289-407-1155',
            ProfilePicture: '',
        },
        {
            DisplayName: 'Moein Shafiei',
            MemberID: 'F002b',
            Email: 'MoeinShafiei@TEI.com',
            Phone: '361-388-4363',
            ProfilePicture: '',
        },
        {
            DisplayName: 'Ian Robinson',
            MemberID: 'F001',
            Email: 'IanRobinson@TEI.com',
            Phone: '253-414-8432',
            ProfilePicture: '',
        },
        {
            DisplayName: 'Mohammad Chavoshi',
            MemberID: 'F001b',
            Email: 'MohammadChavoshi@TEI.com',
            Phone: '781-840-5773',
            ProfilePicture: '',
        },
        {
            DisplayName: 'Hossein Azizkhani',
            MemberID: 'F002',
            Email: 'HosseinAzizkhani@TEI.com',
            Phone: '315-673-8759',
            ProfilePicture: 'https://en.gravatar.com/userimage/202136773/a558891c4ea05046cf2dcc00616153fe.jpg',
        },
        {
            DisplayName: 'Pegah Khavarifar',
            MemberID: 'F002a',
            Email: 'PegahKhavarifar@TEI.com',
            Phone: '289-407-1155',
            ProfilePicture: '',
        },
        {
            DisplayName: 'Moein Shafiei',
            MemberID: 'F002b',
            Email: 'MoeinShafiei@TEI.com',
            Phone: '361-388-4363',
            ProfilePicture: '',
        },
        {
            DisplayName: 'Ian Robinson',
            MemberID: 'F001',
            Email: 'IanRobinson@TEI.com',
            Phone: '253-414-8432',
            ProfilePicture: '',
        },
        {
            DisplayName: 'Mohammad Chavoshi',
            MemberID: 'F001b',
            Email: 'MohammadChavoshi@TEI.com',
            Phone: '781-840-5773',
            ProfilePicture: '',
        },
        {
            DisplayName: 'Hossein Azizkhani',
            MemberID: 'F002',
            Email: 'HosseinAzizkhani@TEI.com',
            Phone: '315-673-8759',
            ProfilePicture: 'https://en.gravatar.com/userimage/202136773/a558891c4ea05046cf2dcc00616153fe.jpg',
        },
        {
            DisplayName: 'Pegah Khavarifar',
            MemberID: 'F002a',
            Email: 'PegahKhavarifar@TEI.com',
            Phone: '289-407-1155',
            ProfilePicture: '',
        },
        {
            DisplayName: 'Moein Shafiei',
            MemberID: 'F002b',
            Email: 'MoeinShafiei@TEI.com',
            Phone: '361-388-4363',
            ProfilePicture: '',
        },
        {
            DisplayName: 'Ian Robinson',
            MemberID: 'F001',
            Email: 'IanRobinson@TEI.com',
            Phone: '253-414-8432',
            ProfilePicture: '',
        },
        {
            DisplayName: 'Mohammad Chavoshi',
            MemberID: 'F001b',
            Email: 'MohammadChavoshi@TEI.com',
            Phone: '781-840-5773',
            ProfilePicture: '',
        },
        {
            DisplayName: 'Hossein Azizkhani',
            MemberID: 'F002',
            Email: 'HosseinAzizkhani@TEI.com',
            Phone: '315-673-8759',
            ProfilePicture: 'https://en.gravatar.com/userimage/202136773/a558891c4ea05046cf2dcc00616153fe.jpg',
        },
        {
            DisplayName: 'Peg 87987',
            MemberID: '22222',
            Email: 'PegahKhavarifar@TEI.com',
            Phone: '289-407-1155',
            ProfilePicture: '',
        },
        {
            DisplayName: 'Moe -00-0-',
            MemberID: 'F002b',
            Email: 'MoeinShafiei@TEI.com',
            Phone: '361-388-4363',
            ProfilePicture: '',
        },
    ];
}
